### ISSUE TITLE
cwl-airflow init error

### ISSUE THREAD

**Issue by mina-theragenetex** [Barski-lab/cwl-airflow#24]
Hi

I got error when I typed "cwl-airflow init".
I installed today and python version is 3.6.5 on mac os x.
please help me.

---

[2019-07-03 17:51:51,809] {main.py:129} INFO
Init Airflow DB
Traceback (most recent call last):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 348, in _revision_for_ident
    revision = self._revision_map[resolved_id]
KeyError: '939bb1e647c8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 138, in _catch_revision_errors
    yield
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 329, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 641, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 298, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 298, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 303, in get_revisions
    for rev_id in resolved_id)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 303, in <genexpr>
    for rev_id in resolved_id)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 358, in _revision_for_ident
    resolved_id)
alembic.script.revision.ResolutionError: No such revision or branch '939bb1e647c8'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/bin/cwl-airflow", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwl_airflow/main.py", line 156, in main
    args.func(args)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwl_airflow/main.py", line 131, in run_init
    initdb(argparse.Namespace())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/bin/cli.py", line 897, in initdb
    db_utils.initdb()
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/utils/db.py", line 103, in initdb
    upgradedb()
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/utils/db.py", line 320, in upgradedb
    command.upgrade(config, 'heads')
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 416, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/migrations/env.py", line 86, in <module>
    run_migrations_online()
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/runtime/environment.py", line 807, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/command.py", line 163, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 333, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 169, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(resolution))
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/util/compat.py", line 121, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/util/compat.py", line 114, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 138, in _catch_revision_errors
    yield
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 329, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 641, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 298, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 298, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 303, in get_revisions
    for rev_id in resolved_id)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 303, in <genexpr>
    for rev_id in resolved_id)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 358, in _revision_for_ident
    resolved_id)
alembic.util.exc.CommandError: Can't locate revision identified by '939bb1e647c8'

**Comment by michael-kotliar** [comment]
Hi @mina-theragenetex,
Thank you for using cwl-airflow. To help me solve your problem, please check if you have the same error when running `airflow initdb` command.

**Comment by mina-theragenetex** [comment]
**$ airflow initdb**
[2019-07-04 11:20:09,446] {__init__.py:45} INFO - Using executor SequentialExecutor
DB: sqlite:////Users/mina/airflow/airflow.db
[2019-07-04 11:20:09,861] {db.py:312} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 348, in _revision_for_ident
    revision = self._revision_map[resolved_id]
KeyError: '939bb1e647c8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 138, in _catch_revision_errors
    yield
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 329, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 641, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 298, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 298, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 303, in get_revisions
    for rev_id in resolved_id)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 303, in <genexpr>
    for rev_id in resolved_id)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 358, in _revision_for_ident
    resolved_id)
alembic.script.revision.ResolutionError: No such revision or branch '939bb1e647c8'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/bin/airflow", line 27, in <module>
    args.func(args)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/bin/cli.py", line 897, in initdb
    db_utils.initdb()
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/utils/db.py", line 103, in initdb
    upgradedb()
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/utils/db.py", line 320, in upgradedb
    command.upgrade(config, 'heads')
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 416, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/migrations/env.py", line 86, in <module>
    run_migrations_online()
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/airflow/migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/runtime/environment.py", line 807, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/command.py", line 163, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 333, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 169, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(resolution))
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/util/compat.py", line 121, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/util/compat.py", line 114, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 138, in _catch_revision_errors
    yield
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/base.py", line 329, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 641, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 298, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 298, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 303, in get_revisions
    for rev_id in resolved_id)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 303, in <genexpr>
    for rev_id in resolved_id)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/alembic/script/revision.py", line 358, in _revision_for_ident
    resolved_id)
alembic.util.exc.CommandError: Can't locate revision identified by '939bb1e647c8'


---

**$ pip show cwl-airflow**
Name: cwl-airflow
Version: 1.0.16
Summary: Python package to extend Airflow functionality with CWL v1.0 support
Home-page: https://github.com/Barski-lab/cwl-airflow
Author: Michael Kotliar
Author-email: misha.kotliar@gmail.com
License: Apache-2.0
Location: /usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages
Requires: apache-airflow, uuid, cwltool, jsonmerge
Required-by:

**Comment by michael-kotliar** [comment]
Unfortunately I cannot replicate this error in my version of Python, but I would recommend you to manually drop the Airflow's database and to run `cwl-airflow init` one more time. The problem seems to be similar to the one mentioned here https://stackoverflow.com/a/32356600/8808721
Also, I would try to run `airflow resetdb` or `airflow upgradedb` (please, share the  log of these commands). Another options is to install CWL-Airflow not in the Python from Miniconda, but the one that you have in your OS by default. Additionally, you can download DMG file with the latest release of CWL-Airflow and install it as Application. Please note, that the documentation for the latest release is still in progress and may not correspond to the latest changes. Feel free to post here all the issues you have. It will help us to make our program better.

**Comment by mina-theragenetex** [comment]
Thank you
I tried to remove existing db and ~/airflow also
and then I run `cwl-airflow init` It works!

But, I got another error again.
When I run `cwl-airflow submit WORKFLOW JOB`, `Not found: 'WORKFLOW'` error has occurred.

```sh
$ cwl-airflow submit WORKFLOW JOB
[2019-07-04 13:14:34,310] {main.py:136} INFO
Load workflow
- workflow: /Users/mina/cwl-airflow/WORKFLOW
- job:      /Users/mina/cwl-airflow/JOB
- uid:      4803526c-c3c9-476a-957e-a78a34c53fee
Traceback (most recent call last):
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/bin/cwl-airflow", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwl_airflow/main.py", line 156, in main
    args.func(args)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwl_airflow/main.py", line 137, in submit_job
    exit_if_unsupported_feature(args.workflow)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwl_airflow/utils/utils.py", line 123, in exit_if_unsupported_feature
    tool = load_cwl(cwl_file).tool
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwl_airflow/utils/utils.py", line 118, in load_cwl
    return load.load_tool(cwl_file, loading_context)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwltool/load_tool.py", line 364, in load_tool
    fetcher_constructor=loadingContext.fetcher_constructor)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwltool/load_tool.py", line 116, in fetch_document
    document_loader=document_loader)
  File "/usr/local/miniconda2/envs/cwl-airflow3.6/lib/python3.6/site-packages/cwltool/load_tool.py", line 95, in resolve_tool_uri
    raise ValidationException("Not found: '%s'" % argsworkflow)
schema_salad.validate.ValidationException: Not found: '/Users/mina/cwl-airflow/WORKFLOW'
```

The ~/cwl-airflow directory has been empty..
Could you let me know what did I do wrong?

**Comment by michael-kotliar** [comment]
Cool! I'm glad I could help you!
