### ISSUE TITLE
Connect workflow output to workflow input directly

### ISSUE THREAD

**Issue by michael-kotliar** [Barski-lab/cwl-airflow#42]
**Describe the bug**
This should work
```
input:
  effective_genome_size:
    type: string
outputs:
  genome_size:
    type: string
    outputSource: effective_genome_size
```

**To Reproduce**
Run this workflow https://github.com/datirium/workflows/blob/94c3b7798e39bbe8afac8e7479a4ef9e3dc96923/workflows/genome-indices.cwl

**Expected behavior**
Shouldn't fail

**Screenshots and logs**
```
[2020-09-21 13:27:18,452] {dagbag.py:239} ERROR - Failed to import: /users/tester/airflow/dags/genome-indices.py
Traceback (most recent call last):
  File "/users/tester/venv/cwl-airflow/lib/python3.6/site-packages/airflow/models/dagbag.py", line 236, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/users/tester/venv/cwl-airflow/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/users/tester/airflow/dags/genome-indices.py", line 5, in <module>
    dag_id="genome-indices"
  File "/users/tester/venv/cwl-airflow/lib/python3.6/site-packages/cwl_airflow/extensions/cwldag.py", line 64, in __init__
    self.__assemble()
  File "/users/tester/venv/cwl-airflow/lib/python3.6/site-packages/cwl_airflow/extensions/cwldag.py", line 139, in __assemble
    self.gatherer.set_upstream(task_by_out_id[output_source_id])              # connected to gatherer
KeyError: 'effective_genome_size'

```

**Desktop (please complete the following information):**
 - Ubuntu
 - Python 3.6.9
 - cwl-airflow from commit https://github.com/Barski-lab/cwl-airflow/tree/ce87759d21b188c111298bfa474097a5b3e1d0b1

**Additional context**
None

**Comment by michael-kotliar** [comment]
Fixed
